apiVersion: apps/v1
kind: Deployment
metadata:
  name: medea
spec:
  template:
    spec:
      containers:
        - name: medea
          env:
            - name: ENV_NAME
              value: production