apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
nameSuffix: -stage
commonLabels:
  app: medea-stage
patchesJson6902:
  - path: ingress-patch.json
    target:
      kind: Ingress
      name: medea-ingress
      version: v1beta1
      group: extensions
patchesStrategicMerge:
  - deployment-patch.yaml
